# Generated by Django 4.0.4 on 2022-05-20 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_todo_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='todo',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('in progress', 'in progress'), ('completed', 'completed')], max_length=50),
        ),
    ]
